# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9155ba1fd30538cf00373f72ac507434b6b7412cd4b22169c41f48609374b3753f1a86f7a24d3b5f2a4285e4153c4ef461408efee8fc9109ed995250bc8cfc71

test:
  secret_key_base: 24a1eecc57b9ee4ca3bdedd814a67bb8c64a7fbc8ab45e5923e3eff1a1e837d193eff6c0b64d168849ce77b97889ccf4dbe90195d56adf9280dcc7c690f24e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
